version: '3'
services:
  web:
    image: "kdarkhan/contacts-sample:2.6.x"
    depends_on:
        - db
  db:
    image: "postgres:10.1"
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=contacts
    ports:
     - "5432:5432"
