version: '3'
services:
  web:
    image: "kdarkhan/contacts-sample:latest"
    depends_on:
        - "db"
    ports:
        - "9000:9000"
  db:
    image: "postgres:10.1"
    environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=contacts
    ports:
     - "5432:5432"
